players = [
    "Ruturaj Gaikwad", "Noor Ahmad", "Khaleel Ahmed", "Ravichandran Ashwin", "Vansh Bedi", "Mukesh Choudhary",
    "Devon Conway", "Sam Curran", "MS Dhoni", "Shivam Dube", "Nathan Ellis", "Ramakrishna Ghosh", "Shreyas Gopal",
    "Deepak Hooda", "Ravindra Jadeja", "Anshul Kamboj", "Kamlesh Nagarkoti", "Jamie Overton", "Matheesha Pathirana",
    "Shaik Rasheed", "Rachin Ravindra", "Vijay Shankar", "Andre Siddarth", "Gurjapneet Singh", "Rahul Tripathi",
    "Axar Patel", "Dushmantha Chameera", "Faf du Plessis", "Donovan Ferreira", "Jake Fraser-McGurk", "Mukesh Kumar",
    "Manvanth Kumar L", "Ajay Mandal", "Karun Nair", "Darshan Nalkande", "T. Natarajan", "Vipraj Nigam",
    "Abhishek Porel", "KL Rahul", "Sameer Rizvi", "Ashutosh Sharma", "Mohit Sharma", "Mitchell Starc", "Madhav Tiwari",
    "Tristan Stubbs", "Tripurana Vijay", "Kuldeep Yadav", "Harry Brook", "Shubman Gill", "Gurnoor Brar",
    "Jos Buttler", "Gerald Coetzee", "Karim Janat", "Arshad Khan", "Rashid Khan", "Shahrukh Khan",
    "Kulwant Khejroliya", "Sai Kishore", "Prasidh Krishna", "Kumar Kushagra", "Mahipal Lomror", "Glenn Phillips",
    "Kagiso Rabada", "Anuj Rawat", "Sherfane Rutherford", "Ishant Sharma", "Nishant Sindhu", "Mohammed Siraj",
    "Sai Sudharsan", "Washington Sundar", "Manav Suthar", "Rahul Tewatia", "Jayant Yadav", "Ajinkya Rahane",
    "Moeen Ali", "Vaibhav Arora", "Varun Chakravarthy", "Quinton de Kock", "Rahmanullah Gurbaz", "Venkatesh Iyer",
    "Spencer Johnson", "Umran Malik", "Mayank Markande", "Sunil Narine", "Anrich Nortje", "Manish Pandey",
    "Rovman Powell", "Angkrish Raghuvanshi", "Harshit Rana", "Anukul Roy", "Andre Russell", "Ramandeep Singh",
    "Rinku Singh", "Luvnith Sisodia", "Chetan Sakariya", "Rishabh Pant", "Shahbaz Ahmed", "Ayush Badoni",
    "Ravi Bishnoi", "Matthew Breetzke", "Yuvraj Chaudhary", "Akash Deep", "Rajvardhan Hangargekar", "Avesh Khan",
    "Mohsin Khan", "Arshin Kulkarni", "Shamar Joseph", "Aryan Juyal", "Aiden Markram", "Mitchell Marsh",
    "David Miller", "Nicholas Pooran", "Abdul Samad", "M Siddharth", "Akash Singh", "Digvesh Singh", "Himmat Singh",
    "Mayank Yadav", "Prince Yadav", "Shardul Thakur", "Hardik Pandya", "Raj Angad Bawa", "Trent Boult",
    "Jasprit Bumrah", "Deepak Chahar", "Naman Dhir", "Allah Mohammad Ghazanfar", "Will Jacks", "Bevon Jacobs",
    "Ashwani Kumar", "Robin Minz", "Vignesh Puthur", "Satyanarayana Raju", "Ryan Rickelton", "Mitchell Santner",
    "Karn Sharma", "Rohit Sharma", "Krishnan Shrijith", "Arjun Tendulkar", "Reece Topley", "Tilak Varma",
    "Lizaad Williams", "Suryakumar Yadav", "Mujeeb Ur Rahman", "Corbin Bosch", "Shreyas Iyer", "Priyansh Arya",
    "Pyla Avinash", "Xavier Bartlett", "Harpreet Brar", "Yuzvendra Chahal", "Praveen Dubey", "Lockie Ferguson",
    "Aaron Hardie", "Josh Inglis", "Marco Jansen", "Musheer Khan", "Glenn Maxwell", "Azmatullah Omarzai",
    "Kuldeep Sen", "Suryansh Shedge", "Arshdeep Singh", "Harnoor Singh", "Prabhsimran Singh", "Shashank Singh",
    "Marcus Stoinis", "Yash Thakur", "Vishnu Vinod", "Nehal Wadhera", "Vijaykumar Vyshak", "Sanju Samson",
    "Jofra Archer", "Yudhvir Charak", "Tushar Deshpande", "Shubham Dubey", "Fazalhaq Farooqi", "Wanindu Hasaranga",
    "Shimron Hetmyer", "Yashasvi Jaiswal", "Dhruv Jurel", "Kumar Kartikeya", "Akash Madhwal", "Kwena Maphaka",
    "Riyan Parag", "Nitish Rana", "Kunal Rathore", "Ashok Sharma", "Sandeep Sharma", "Vaibhav Suryavanshi",
    "Maheesh Theekshana", "Rajat Patidar", "Virat Kohli", "Jacob Bethell", "Manoj Bhandage", "Swastik Chikara",
    "Rasikh Salam Dar", "Tim David", "Yash Dayal", "Josh Hazlewood", "Bhuvneshwar Kumar", "Liam Livingstone",
    "Lungi Ngidi", "Devdutt Padikkal", "Krunal Pandya", "Mohit Rathee", "Phil Salt", "Jitesh Sharma",
    "Suyash Sharma", "Romario Shepherd", "Abhinandan Singh", "Swapnil Singh", "Nuwan Thushara", "Pat Cummins",
    "Zeeshan Ansari", "Sachin Baby", "Brydon Carse", "Rahul Chahar", "Travis Head", "Ishan Kishan",
    "Heinrich Klaasen", "Eshan Malinga", "Abhinav Manohar", "Kamindu Mendis", "Harshal Patel",
    "Nitish Kumar Reddy", "Mohammad Shami", "Abhishek Sharma", "Simarjeet Singh", "Atharva Taide",
    "Jaydev Unadkat", "Aniket Verma", "Adam Zampa", "Wiaan Mulder"
]

